### PR TITLE
#305 Fixing unexpectedly high weights for XCM pallet

### LINKED ISSUE #305: 🐞 [Bug]: Unexpectedly high weights/fees for `pallet_xcm`
### templates

- [X] Generic Runtime Template
- [X] Evm Template

### What happened?

Discovered by @DrW3RK (thank you!):
In both generic and evm templates, under `pallet-xcm` [weights](https://github.com/OpenZeppelin/polkadot-runtime-templates/blob/main/generic-template/runtime/src/weights/pallet_xcm.rs#L65), we have unexpectedly high weights assigned to:
- `teleport_assets`
- `reserve_transfer_assets`
- `transfer_assets`
- `execute`
- `execute_blob`

AFAIK, these weights are generated on a specific machine with benchmarking commands. 

We should find the reason for why the benchmarking generated these absurd weights. Or, if they are expected to be that high, we should maybe explain that better in our docs or inline docs.

### Expected behavior

_No response_

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines

### PR DESCRIPTION
**Pull request by KitHat**
Updated configuration and benchmarking for XCM pallet.
In relation to original issue:

Fixed benchmarks:
- `execute`
- `transfer_assets`
- `reserve_transfer_assets`

Benchmarks that were left unchanged:
- `execute_blob` -- it was removed in `stable-2407`.
- `teleport_assets` -- we are not going to allow to teleport assets over the XCM, so we will not spend time on fixing this benchmarks. If you are willing to do it, feel free to contribute.

Fixes #305  

#### PR Checklist

- [x] Tests
- [x] Documentation
- [x] Pallets, that require benchmarks, are added to `scripts/assets/pallets.txt` (Pallet require benchmark if it has WeightInfo config type)

### CODE REVIEW

File: evm-template/runtime/src/apis.rs [hunk 1]
```diff
@@ -503,18 +503,111 @@ impl_runtime_apis! {
...
+                    let asset_type = AssetType::Xcm(location_v3);
+
+                    let local_asset_id: crate::types::AssetId = asset_type.clone().into();
+                    let manager_id = AssetManager::account_id();
+                    let _ = Assets::force_create(RuntimeOrigin::root(), local_asset_id.clone().into(), sp_runtime::MultiAddress::Id(manager_id.clone()), true, 1);
+                    let _ = Assets::mint(
+                        RawOrigin::Signed(manager_id.clone()).into(),
+                        local_asset_id.into(),
+                        sp_runtime::MultiAddress::Id(who),
+                        3001010000000,
```
Comment (ozgunozerk) [inline evm-template/runtime/src/apis.rs:525]: nitpick: usually a better idea to use the magic number as a constant declared with an explanatory name

File: evm-template/runtime/src/apis.rs [hunk 2]
```diff
@@ -503,18 +503,111 @@ impl_runtime_apis! {
...
+                    );
+                    AssetManager::set_asset_type_asset_id(asset_type.clone(), local_asset_id.into());
+
+                    // open a mock parachain channel
+                    ParachainSystem::open_outbound_hrmp_channel_for_benchmarks_or_tests(
+                        RandomParaId::get().into()
+                    );
+
+                    // set up transfer asset
+                    let initial_asset_amount: u128 = 4001070000100;
```
Comment (ozgunozerk) [inline evm-template/runtime/src/apis.rs:535]: same here

File: generic-template/runtime/src/configs/xcm_config.rs [hunk 3]
```diff
@@ -223,11 +223,14 @@ impl pallet_xcm::Config for Runtime {
     type Weigher = FixedWeightBounds<UnitWeightCost, RuntimeCall, MaxInstructions>;
     /// Rerun benchmarks if you are making changes to runtime configuration.
     type WeightInfo = weights::pallet_xcm::WeightInfo<Runtime>;
+    #[cfg(feature = "runtime-benchmarks")]
+    type XcmExecuteFilter = Everything;
+    #[cfg(not(feature = "runtime-benchmarks"))]
     type XcmExecuteFilter = Nothing;
     // ^ Disable dispatchable execute on the XCM pallet.
     // Needs to be `Everything` for local testing.
```
Comment (ozgunozerk) [inline generic-template/runtime/src/configs/xcm_config.rs:231]: should we update this comment?

**Review by ozgunozerk — APPROVED** [review]
LGTM overall

File: generic-template/runtime/src/configs/xcm_config.rs (hunk 3 above)
Comment (KitHat) [reply generic-template/runtime/src/configs/xcm_config.rs:230]: Updated

File: evm-template/runtime/src/apis.rs (hunk 2 above)
Comment (KitHat) [reply evm-template/runtime/src/apis.rs]: Moved to a constant type

File: evm-template/runtime/src/apis.rs (hunk 1 above)
Comment (KitHat) [reply evm-template/runtime/src/apis.rs]: Moved to a constant type
